services:

  php:
    build: tests/docker
    depends_on:
      - clickhouse01
      - clickhouse02
      - zookeeper
    volumes:
      - ./:/src

  clickhouse01:
    image: clickhouse/clickhouse-server:24.8
    ports:
      - "18123:8123"
    depends_on:
      - zookeeper
    volumes:
      - ./tests/docker/clickhouse01:/etc/clickhouse-server

  clickhouse02:
    image: clickhouse/clickhouse-server:24.8
    ports:
      - "18124:8123"
    depends_on:
      - zookeeper
    volumes:
      - ./tests/docker/clickhouse02:/etc/clickhouse-server

  zookeeper:
    image: zookeeper:3.7
